# Site settings
title: Gabriel Ian
email: info@gabrielian.net
description: > # this means to ignore newlines until "baseurl:"
  A personal portfolio and blog.

url:  "http://gabrielian.net"
baseurl:  "/GabrielIan"
twitter_username: GabrielIRoth
github_username:  ConceptKreator

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  resume:
    output: true
    permalink: /resume/:path/